"
This class is a mock object for the MWParser tests.
"
Class {
	#name : #MWParserTestMockObject,
	#superclass : #Object,
	#instVars : [
		'id',
		'name'
	],
	#category : #'MensaWidget-Tests',
	#'squeak_changestamp' : 'Max 5/29/2024 08:54'
}

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 5/28/2024 18:29'
}
MWParserTestMockObject >> id [
	^ id
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 5/28/2024 18:29'
}
MWParserTestMockObject >> id: anObject [
	id := anObject
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 5/28/2024 18:29'
}
MWParserTestMockObject >> name [
	^ name
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 5/28/2024 18:29'
}
MWParserTestMockObject >> name: anObject [
	name := anObject
]
