"
A MWParserTestMockObject2 is a test object for the MWParserTest.

Instance Variables
	id:		<Number>
	name:		<String>

id
	- the id provided by the data input

name
	- the name provided by the data input

"
Class {
	#name : #MWParserTestMockObject,
	#superclass : #Object,
	#instVars : [
		'id',
		'name'
	],
	#category : #'MensaWidget-Tests',
	#'squeak_changestamp' : 'Max 5/29/2024 19:53'
}

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 5/29/2024 13:00'
}
MWParserTestMockObject >> id [

	^ id
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 5/29/2024 13:00'
}
MWParserTestMockObject >> id: anObject [

	id := anObject
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 5/29/2024 13:00'
}
MWParserTestMockObject >> name [

	^ name
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 5/29/2024 13:00'
}
MWParserTestMockObject >> name: anObject [

	name := anObject
]
