Class {
	#name : #MWPrice,
	#superclass : #Object,
	#instVars : [
		'students',
		'employees',
		'others',
		'pupils'
	],
	#category : #MensaWidget
}

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 6/10/2024 18:47'
}
MWPrice >> employees [
	^ employees
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 6/10/2024 18:47'
}
MWPrice >> employees: anObject [
	employees := anObject
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 6/10/2024 18:47'
}
MWPrice >> others [
	^ others
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 6/10/2024 18:47'
}
MWPrice >> others: anObject [
	others := anObject
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 6/10/2024 18:47'
}
MWPrice >> pupils [
	^ pupils
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 6/10/2024 18:47'
}
MWPrice >> pupils: anObject [
	pupils := anObject
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 6/10/2024 19:34'
}
MWPrice >> students [
	^ students
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'Max 6/10/2024 19:34'
}
MWPrice >> students: anObject [
	students := anObject
]
